version: "3.9"

services:
  api:
    build: .
    image: vendorhub-backoffice-image-repos
    container_name: vendorhub-backoffice-api
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
      PORT: 8080
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${DOCKER_GOOGLE_REDIRECT_URI}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      CLOUDINARY_API_ENVIRONMENT_VARIABLE_CLOUDINARY_URL: ${CLOUDINARY_API_ENVIRONMENT_VARIABLE_CLOUDINARY_URL}
      GRAFANA_LOKI_URL: ${GRAFANA_LOKI_URL}
      GRAFANA_LOKI_USER: ${GRAFANA_LOKI_USER}
      GRAFANA_LOKI_API_KEY: ${GRAFANA_LOKI_API_KEY}
      LOG_LEVEL: ${LOG_LEVEL}
    restart: unless-stopped